"""create seat-allocation table\

Revision ID: 38d0f225e115
Revises: 
Create Date: 2026-04-02 22:30:15.212627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d0f225e115'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holds',
    sa.Column('hold_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('hold_id'),
    sa.UniqueConstraint('event_id', 'seat_id', 'order_id', name='uq_active_hold'),
    schema='seat_allocation_service'
    )
    op.create_table('reallocation_logs',
    sa.Column('reallocation_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('old_seat_id', sa.UUID(), nullable=True),
    sa.Column('new_seat_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('reallocation_id'),
    schema='seat_allocation_service'
    )
    op.create_table('seat_assignments',
    sa.Column('seat_assign_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('hold_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id', 'seat_id', 'order_id'], ['seat_allocation_service.holds.event_id', 'seat_allocation_service.holds.seat_id', 'seat_allocation_service.holds.order_id'], ),
    sa.ForeignKeyConstraint(['hold_id'], ['seat_allocation_service.holds.hold_id'], ),
    sa.PrimaryKeyConstraint('seat_assign_id'),
    schema='seat_allocation_service'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seat_assignments', schema='seat_allocation_service')
    op.drop_table('reallocation_logs', schema='seat_allocation_service')
    op.drop_table('holds', schema='seat_allocation_service')
    # ### end Alembic commands ###
