"""create swap table

Revision ID: 0ecaf9edae92
Revises: 
Create Date: 2026-03-21 22:15:18.242042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecaf9edae92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swap_confirmations',
    sa.Column('confirmation_id', sa.UUID(), nullable=False),
    sa.Column('swap_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('confirmation_id'),
    schema='swap_service'
    )
    op.create_table('swap_matches',
    sa.Column('swap_id', sa.UUID(), nullable=False),
    sa.Column('request_a', sa.UUID(), nullable=True),
    sa.Column('request_b', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('swap_id'),
    schema='swap_service'
    )
    op.create_table('swap_payments',
    sa.Column('swap_payment_id', sa.UUID(), nullable=False),
    sa.Column('swap_id', sa.UUID(), nullable=True),
    sa.Column('payer_order_id', sa.UUID(), nullable=True),
    sa.Column('payee_order_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('swap_payment_id'),
    schema='swap_service'
    )
    op.create_table('swap_requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('current_seat_id', sa.UUID(), nullable=False),
    sa.Column('desired_tier', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('request_id'),
    schema='swap_service'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap_requests', schema='swap_service')
    op.drop_table('swap_payments', schema='swap_service')
    op.drop_table('swap_matches', schema='swap_service')
    op.drop_table('swap_confirmations', schema='swap_service')
    # ### end Alembic commands ###
