"""init

Revision ID: a382f035b723
Revises: 
Create Date: 2026-04-06 19:20:32.248607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a382f035b723'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap_payments', schema='swap_service')
    op.alter_column('swap_requests', 'order_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.BigInteger(),
               existing_nullable=False,
               schema='swap_service',
               postgresql_using='order_id::bigint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swap_requests', 'order_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='swap_service')
    op.create_table('swap_payments',
    sa.Column('swap_payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('swap_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payer_order_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payee_order_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('swap_payment_id', name=op.f('swap_payments_pkey')),
    schema='swap_service'
    )
    # ### end Alembic commands ###
