"""empty message

Revision ID: da9f0aff5ba4
Revises: 1ba600a6fd99
Create Date: 2026-04-04 20:51:36.972034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da9f0aff5ba4'
down_revision: Union[str, Sequence[str], None] = '1ba600a6fd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swap_confirmations', 'swap_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='swap_service')
    op.alter_column('swap_confirmations', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='swap_service')
    op.alter_column('swap_confirmations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='swap_service')
    op.alter_column('swap_confirmations', 'responded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='swap_service')
    op.create_unique_constraint('uq_swap_user_response', 'swap_confirmations', ['swap_id', 'user_id'], schema='swap_service')
    op.alter_column('swap_matches', 'request_a',
               existing_type=sa.UUID(),
               nullable=False,
               schema='swap_service')
    op.alter_column('swap_matches', 'request_b',
               existing_type=sa.UUID(),
               nullable=False,
               schema='swap_service')
    op.alter_column('swap_matches', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               schema='swap_service')
    op.create_unique_constraint('uq_swap_pair', 'swap_matches', ['request_a', 'request_b'], schema='swap_service')
    op.alter_column('swap_payments', 'swap_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='swap_service')
    op.alter_column('swap_payments', 'payer_order_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='swap_service')
    op.alter_column('swap_payments', 'payee_order_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='swap_service')
    op.alter_column('swap_payments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               schema='swap_service')
    op.add_column('swap_requests', sa.Column('current_tier', sa.String(length=20), nullable=False), schema='swap_service')
    op.alter_column('swap_requests', 'desired_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='swap_service')
    op.alter_column('swap_requests', 'expiry',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='swap_service')
    op.create_index('ix_swap_requests_event_status', 'swap_requests', ['event_id', 'status'], unique=False, schema='swap_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_swap_requests_event_status', table_name='swap_requests', schema='swap_service')
    op.alter_column('swap_requests', 'expiry',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='swap_service')
    op.alter_column('swap_requests', 'desired_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='swap_service')
    op.drop_column('swap_requests', 'current_tier', schema='swap_service')
    op.alter_column('swap_payments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               schema='swap_service')
    op.alter_column('swap_payments', 'payee_order_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='swap_service')
    op.alter_column('swap_payments', 'payer_order_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='swap_service')
    op.alter_column('swap_payments', 'swap_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='swap_service')
    op.drop_constraint('uq_swap_pair', 'swap_matches', schema='swap_service', type_='unique')
    op.alter_column('swap_matches', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               schema='swap_service')
    op.alter_column('swap_matches', 'request_b',
               existing_type=sa.UUID(),
               nullable=True,
               schema='swap_service')
    op.alter_column('swap_matches', 'request_a',
               existing_type=sa.UUID(),
               nullable=True,
               schema='swap_service')
    op.drop_constraint('uq_swap_user_response', 'swap_confirmations', schema='swap_service', type_='unique')
    op.alter_column('swap_confirmations', 'responded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='swap_service')
    op.alter_column('swap_confirmations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='swap_service')
    op.alter_column('swap_confirmations', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='swap_service')
    op.alter_column('swap_confirmations', 'swap_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='swap_service')
    # ### end Alembic commands ###
