"""create users table

Revision ID: d6a56b3329e5
Revises: 0912c744ee12
Create Date: 2026-03-21 14:43:34.800744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6a56b3329e5'
down_revision: Union[str, Sequence[str], None] = '0912c744ee12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('testpw', sa.String(length=255), nullable=False), schema='user_service')
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               schema='user_service')
    op.drop_column('users', 'password', schema='user_service')
    op.drop_column('users', 'created_at', schema='user_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True), schema='user_service')
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='user_service')
    op.alter_column('users', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='user_service')
    op.drop_column('users', 'testpw', schema='user_service')
    # ### end Alembic commands ###
