"""create user table

Revision ID: efd82c3f9e53
Revises: d6a56b3329e5
Create Date: 2026-03-21 15:29:07.712361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd82c3f9e53'
down_revision: Union[str, Sequence[str], None] = 'd6a56b3329e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False,
               schema='user_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("nextval('user_service.users_user_id_seq'::regclass)"),
               existing_nullable=False,
               schema='user_service')
    # ### end Alembic commands ###
