"""empty message

Revision ID: c6adde102fd4
Revises: f1a2b3c4d5e6
Create Date: 2026-04-04 21:51:20.774701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6adde102fd4'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_showtimes', 'times',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False,
               schema='events_service')
    op.alter_column('event_visual_sections', 'multiline',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='events_service')
    op.alter_column('event_visual_sections', 'hidden',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='events_service')
    op.alter_column('seats', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='events_service')
    op.drop_constraint(op.f('fk_seats_event_id'), 'seats', schema='events_service', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_seats_event_id'), 'seats', 'events', ['event_id'], ['event_id'], source_schema='events_service', referent_schema='events_service', ondelete='CASCADE')
    op.alter_column('seats', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='events_service')
    op.alter_column('event_visual_sections', 'hidden',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False,
               schema='events_service')
    op.alter_column('event_visual_sections', 'multiline',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False,
               schema='events_service')
    op.alter_column('event_showtimes', 'times',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False,
               schema='events_service')
    # ### end Alembic commands ###
