import os

class Config:
    EVENT_SERVICE_URL = os.getenv("EVENT_SERVICE_URL")
    SEAT_SERVICE_URL = os.getenv("SEAT_SERVICE_URL")
    ORDER_SERVICE_URL = os.getenv("ORDER_SERVICE_URL")
    PAYMENT_SERVICE_URL = os.getenv("PAYMENT_SERVICE_URL")
    NOTIFICATION_SERVICE_URL = os.getenv("NOTIFICATION_SERVICE_URL")
    RABBITMQ_HOST = os.getenv("RABBITMQ_HOST", "localhost")