# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/user.proto\x12\x04user\"3\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"F\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x12\n\x10ListUsersRequest\"$\n\x11\x44\x65leteUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\".\n\x12\x43reateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"8\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x18\n\x04user\x18\x02 \x01(\x0b\x32\n.user.User\"+\n\x0fGetUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\".\n\x11ListUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xbb\x02\n\x0bUserService\x12?\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x12\x34\n\tLoginUser\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12<\n\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponse\x12?\n\nDeleteUser\x12\x17.user.DeleteUserRequest\x1a\x18.user.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=27
  _globals['_USER']._serialized_end=78
  _globals['_CREATEUSERREQUEST']._serialized_start=80
  _globals['_CREATEUSERREQUEST']._serialized_end=150
  _globals['_LOGINREQUEST']._serialized_start=152
  _globals['_LOGINREQUEST']._serialized_end=199
  _globals['_GETUSERREQUEST']._serialized_start=201
  _globals['_GETUSERREQUEST']._serialized_end=234
  _globals['_LISTUSERSREQUEST']._serialized_start=236
  _globals['_LISTUSERSREQUEST']._serialized_end=254
  _globals['_DELETEUSERREQUEST']._serialized_start=256
  _globals['_DELETEUSERREQUEST']._serialized_end=292
  _globals['_CREATEUSERRESPONSE']._serialized_start=294
  _globals['_CREATEUSERRESPONSE']._serialized_end=340
  _globals['_LOGINRESPONSE']._serialized_start=342
  _globals['_LOGINRESPONSE']._serialized_end=398
  _globals['_GETUSERRESPONSE']._serialized_start=400
  _globals['_GETUSERRESPONSE']._serialized_end=443
  _globals['_LISTUSERSRESPONSE']._serialized_start=445
  _globals['_LISTUSERSRESPONSE']._serialized_end=491
  _globals['_DELETEUSERRESPONSE']._serialized_start=493
  _globals['_DELETEUSERRESPONSE']._serialized_end=530
  _globals['_USERSERVICE']._serialized_start=533
  _globals['_USERSERVICE']._serialized_end=848
# @@protoc_insertion_point(module_scope)
