"""init

Revision ID: 5095012c8d91
Revises: 
Create Date: 2026-04-06 19:47:14.949346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5095012c8d91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'order_id',
               existing_type=sa.TEXT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               schema='payment_service')    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'order_id',
               existing_type=sa.BigInteger(),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='payment_service')
    # ### end Alembic commands ###
