"""create payment table

Revision ID: d5e0b09eeb30
Revises: 
Create Date: 2026-03-21 22:34:27.791001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e0b09eeb30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('external_ref_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','SUCCESS','FAILED')", name='check_transaction_status'),
    sa.CheckConstraint("type IN ('PAYMENT','REFUND','ADJUSTMENT','SWAP_SETTLEMENT')", name='check_transaction_type'),
    sa.PrimaryKeyConstraint('transaction_id'),
    schema='payment_service'
    )
    op.create_table('payment_ledger',
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("entry_type IN ('DEBIT','CREDIT')", name='check_entry_type'),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_service.transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('ledger_id'),
    schema='payment_service'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_ledger', schema='payment_service')
    op.drop_table('transactions', schema='payment_service')
    # ### end Alembic commands ###
