_format_version: "2.1"
_transform: true

services:

- name: events-service
  url: http://events-service:5000
  routes:
  - name: events-root
    paths:
    - /events
  - name: events-id
    paths:
    - "~/events/[^/]+$"
  - name: events-seat
    paths:
    - "~/events/[^/]+/[^/]+$"

- name: order-service
  url: http://order-service:5000
  routes:
  - name: order-create
    paths:
    - /order
    methods: ["POST"]
  - name: order-id
    paths:
    - "~/order/[^/]+$"
    methods: ["POST","DELETE"]
  - name: order-swap
    paths:
    - "~/order/[^/]+/swap$"
    methods: ["POST"]

- name: seat-allocation-service
  url: http://seat-allocation-service:5000
  routes:
  - name: hold-id
    paths:
    - "~/hold/[^/]+$"
    methods: ["POST","DELETE"]

- name: swap-service
  url: http://swap-service:5000
  routes:
  - name: swap-id
    paths:
    - "~/swap/[^/]+$"
    methods: ["POST","DELETE"]
  - name: swap-confirm
    paths:
    - "~/swap/[^/]+/confirm$"
    methods: ["POST"]

- name: payment-service
  url: http://payment-service:5000
  routes:
  - name: payment-id
    paths:
    - "~/payment/[^/]+$"
    methods: ["POST"]
  - name: payment-refund
    paths:
    - "~/payment/[^/]+/refund$"
    methods: ["POST"]
  - name: payment-adjust
    paths:
    - "~/payment/[^/]+/adjustment$"
    methods: ["POST"]

- name: notification-service
  url: http://notification-service:5000
  routes:
  - name: notification
    paths:
    - /notification
    methods: ["POST"]

plugins:
- name: file-log
  config:
    path: /dev/stdout