"""create order table

Revision ID: b33e5b8c889c
Revises: 73c6f964211a
Create Date: 2026-04-02 22:13:54.416540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33e5b8c889c'
down_revision: Union[str, Sequence[str], None] = '73c6f964211a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               schema='order_service')
    op.alter_column('order_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='order_service')
    op.create_index(op.f('ix_order_service_order_items_order_id'), 'order_items', ['order_id'], unique=False, schema='order_service')
    op.create_index(op.f('ix_order_service_order_items_seat_id'), 'order_items', ['seat_id'], unique=False, schema='order_service')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['order_id'], source_schema='order_service', referent_schema='order_service')
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='order_service')
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               schema='order_service')
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               schema='order_service')
    op.create_index(op.f('ix_order_service_orders_event_id'), 'orders', ['event_id'], unique=False, schema='order_service')
    op.create_index(op.f('ix_order_service_orders_user_id'), 'orders', ['user_id'], unique=False, schema='order_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_service_orders_user_id'), table_name='orders', schema='order_service')
    op.drop_index(op.f('ix_order_service_orders_event_id'), table_name='orders', schema='order_service')
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               schema='order_service')
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               schema='order_service')
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='order_service')
    op.drop_constraint(None, 'order_items', schema='order_service', type_='foreignkey')
    op.drop_index(op.f('ix_order_service_order_items_seat_id'), table_name='order_items', schema='order_service')
    op.drop_index(op.f('ix_order_service_order_items_order_id'), table_name='order_items', schema='order_service')
    op.alter_column('order_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='order_service')
    op.alter_column('order_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               schema='order_service')
    # ### end Alembic commands ###
